version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=first
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Test123
    depends_on:
      - 127.0.0.1
    networks:
      custom_network:
        ipv4_address: 172.20.0.22
  127.0.0.1: 
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: first
      MYSQL_USER: user
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: Test123
    volumes:
      - 127.0.0.1_data:/var/lib/mysql
    networks:
      custom_network:
        ipv4_address: 172.20.0.23
volumes:
  127.0.0.1_data: {}
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

